# -*- coding: utf-8 -*-
"""Challenging1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17KqZvm_QtrBwiLM8mx1Bks43Df6yq-JN
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure(figsize=(9,9))
ax = Axes3D(fig)

#For L1, taking lambda 1 values as 3 and -1
x1=np.array([7,-1])
y1=np.array([-2,2])
z1=np.array([3,-1])
#For L2, taking lambda 2 values as 2 and -1
x2=np.array([8,-1])
y2=np.array([-9,6])
z2=np.array([3,-3])
#Plotting the lines
ax.plot(x1,y1,z1,color='green',label='L1')
ax.plot(x2,y2,z2,color='blue',label='L2')
#Closest points on respective lines
xs = np.array([109/59,139/59])
ys = np.array([34/59,24/59])
zs = np.array([25/59,-45/59])
ax.text(xs[0], ys[0], zs[0], "E")
ax.text(xs[1], ys[1], zs[1], "F")
for x,y,z in zip(xs,ys,zs) :
  label = '  (%0.2f,%0.2f,%0.2f)' % (x,y,z)
  ax.text(x,y,z,label)

ax.scatter(xs,ys,zs,color = "red")

ax.set_xlabel('X axis')
ax.set_ylabel('Y axis')
ax.set_zlabel('Z axis')

plt.show()