# -*- coding: utf-8 -*-
"""Challenging1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17KqZvm_QtrBwiLM8mx1Bks43Df6yq-JN
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
fig.set_size_inches(8,8)
ax = Axes3D(fig)

#For L1, taking lambda_1 values as 3 and -1
x1=np.array([7,-1])
y1=np.array([-2,2])
z1=np.array([3,-1])
#For L2, taking lambda_2 values as 2 and -1
x2=np.array([8,-1])
y2=np.array([-9,6])
z2=np.array([3,-3])
#Plotting the lines
ax.plot(x1,y1,z1,color='green')
ax.plot(x2,y2,z2,color='blue')
#Closest points on respective lines
x = np.array([109/59,139/59])
y = np.array([34/59,24/59])
z = np.array([25/59,-45/59])
ax.scatter(x,y,z,color = "red")

ax.text(x[0], y[0], z[0], "E")
ax.text(x[1], y[1], z[1], "F")
ax.set_xlabel('X axis')
ax.set_ylabel('Y axis')
ax.set_zlabel('Z axis')

plt.show()